version: '3.5'

services:
  front:
      build: ./front
      command: yarn start
      volumes:
        - ./front:/app
      ports:
        - 8000:3000
      tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/app
      - ./api/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
  
volumes:
  mysql-data:
    driver: local